import { GoogleGenerativeAI } from '@google/generative-ai';
import { getSystemInstruction } from './personas';

const API_KEY = import.meta.env.VITE_GEMINI_API_KEY;

/**
 * Send a message to the Gemini API in the voice of the selected character.
 *
 * @param {string} characterName — 'Jay Gatsby' | 'Nick Carraway' | 'Daisy Buchanan'
 * @param {Array<{sender: string, text: string}>} chatHistory — full conversation so far (excluding the latest user message)
 * @param {string} userMessage — the latest message from the user
 * @returns {Promise<string>} — the AI's response text
 */
export async function sendMessage(characterName, chatHistory, userMessage) {
    if (!API_KEY || API_KEY === 'your_api_key_here') {
        throw new Error(
            'Gemini API key is not configured. Please set VITE_GEMINI_API_KEY in your .env file.'
        );
    }

    const genAI = new GoogleGenerativeAI(API_KEY);

    const model = genAI.getGenerativeModel({
        model: 'gemini-2.5-flash',
        systemInstruction: getSystemInstruction(characterName),
    });

    // Convert our message history into the format Gemini expects.
    // We skip the very first AI greeting since it wasn't generated by the model.
    const history = chatHistory
        .filter((_, index) => index > 0) // skip the initial greeting
        .map((msg) => ({
            role: msg.sender === 'user' ? 'user' : 'model',
            parts: [{ text: msg.text }],
        }));

    const chat = model.startChat({ history });

    const result = await chat.sendMessage(userMessage);
    const response = result.response;

    return response.text();
}
